export const styling = {
  display: 'inline-block',
  padding: '12px 24px',
  fontSize: '16px',
  fontWeight: 'bold',
  textAlign: 'center',
  textDecoration: 'none',
  borderRadius: '8px',
  border: 'none',
  color: '#ffffff',
  backgroundColor: '#292938',
  boxShadow: '0 2px 4px rgba(0, 0, 0, 0.15)',
  transition: 'background-color 0.3s ease',
  cursor: 'pointer',
  fontFamily: 'Poppins',
}
